const mongoose=require('mongoose')

const RESTAURANTSchema=mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    cuisine:{
        type:Array,
        required:true,
    },
    foodTypes:{
        type:Array,
        required:true,
    },
    branch:{
        type:Number,
        required:false,
    },
    address:{
        addressLine1:{
            type:String,
            required:true
        },
        addressLine2:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true,
        },
        state:{
            type:String,
            required:true,
        },
        country:{
            type:String,
            required:true,
        },
        area:{
            type:String,
            required:true,
        },
        pincode:{
            type:Number,
            required:true,
        }
    },
    
    contactNumber:{
        type:String,
        required:false,
    },
    logo:{
        type:String,
        required:false,
    },
    createdAt:{
        type:Date,
        default:Date.now(),
    },
    updatedAt:{
        type:Date,
        default:Date.now(),
    }
})

const RestaurantsModel=mongoose.model('restaurants',RESTAURANTSchema);
module.exports=RestaurantsModel